export interface UsageTopic {
  id: string;
  title: string;
  summary: string;
  components: string[];
  markdown: string;
}

export const usageTopics: UsageTopic[] = [
  {
    id: "setup",
    title: "Project setup",
    summary: "Register services, theme, scripts, and the RadzenComponents host.",
    components: ["RadzenTheme", "RadzenComponents"],
    markdown: [
      "## Radzen setup",
      "",
      "**`_Imports.razor`**",
      "```razor",
      "@using Radzen",
      "@using Radzen.Blazor",
      "```",
      "",
      "**`Program.cs`** — one call registers DialogService, NotificationService, TooltipService and ContextMenuService:",
      "```csharp",
      "builder.Services.AddRadzenComponents();",
      "```",
      "",
      "**`App.razor` `<head>`** — pick a theme and include the JS:",
      "```razor",
      '<RadzenTheme Theme="material" @rendermode="InteractiveServer" />',
      '<script src="_content/Radzen.Blazor/Radzen.Blazor.js"></script>',
      "```",
      "",
      "**`MainLayout.razor`** — host interactive UI (dialogs, tooltips, notifications):",
      "```razor",
      '<RadzenComponents @rendermode="InteractiveServer" />',
      "```",
      "",
      "> Gotcha: dialogs/tooltips/notifications silently do nothing if `RadzenComponents` is missing or its render mode does not match your app.",
    ].join("\n"),
  },
  {
    id: "data-binding",
    title: "Two-way data binding",
    summary: "Every input binds with @bind-Value regardless of value type.",
    components: ["RadzenTextBox", "RadzenNumeric", "RadzenDropDown", "RadzenDatePicker", "RadzenCheckBox"],
    markdown: [
      "## Two-way binding",
      "",
      "Radzen inputs use **`@bind-Value`** — not `@bind-Text`/`@bind-Date` — for every component, whatever the underlying type. The companion event is `Change`.",
      "",
      "```razor",
      "<RadzenTextBox @bind-Value=@name />",
      "<RadzenNumeric @bind-Value=@count TValue=\"int\" />",
      "<RadzenDatePicker @bind-Value=@date />",
      "<RadzenDropDown @bind-Value=@selected Data=@items TValue=\"string\" Change=@OnChange />",
      "```",
      "",
      "Structural binds also exist, e.g. `@bind-Expanded` on `RadzenSidebar` and `@bind-Value` for DataGrid selection.",
    ].join("\n"),
  },
  {
    id: "validation",
    title: "Form validation",
    summary: "RadzenTemplateForm with validators linked by Name ↔ Component.",
    components: [
      "RadzenTemplateForm",
      "RadzenRequiredValidator",
      "RadzenEmailValidator",
      "RadzenLengthValidator",
      "RadzenNumericRangeValidator",
      "RadzenCompareValidator",
      "RadzenRegexValidator",
    ],
    markdown: [
      "## Validation",
      "",
      "Validators link to an input by **`Name` (on the input) ↔ `Component` (on the validator)** — not by binding.",
      "",
      "```razor",
      "<RadzenTemplateForm TItem=\"Model\" Data=@model Submit=@OnSubmit InvalidSubmit=@OnInvalidSubmit>",
      "    <RadzenTextBox Name=\"Email\" @bind-Value=@model.Email />",
      "    <RadzenRequiredValidator Component=\"Email\" Text=\"Required\" />",
      "    <RadzenEmailValidator Component=\"Email\" Text=\"Invalid email\" />",
      "    <RadzenButton ButtonType=\"ButtonType.Submit\" Text=\"Save\" />",
      "</RadzenTemplateForm>",
      "```",
      "",
      "Validators: `RadzenRequiredValidator`, `RadzenEmailValidator`, `RadzenLengthValidator`, `RadzenNumericRangeValidator`, `RadzenCompareValidator`, `RadzenRegexValidator`, `RadzenCustomValidator`.",
      "",
      "> Gotchas: for numeric/non-null fields set `DefaultValue=\"0\"` on the required validator; use `Style=\"position:absolute\"` to control message placement.",
    ].join("\n"),
  },
  {
    id: "datagrid",
    title: "DataGrid binding (client and server)",
    summary: "Columns, paging/sorting/filtering, and the LoadData server pattern.",
    components: ["RadzenDataGrid", "RadzenDataGridColumn"],
    markdown: [
      "## DataGrid",
      "",
      "**Client-side** — bind `Data` and declare columns, enable features with flags:",
      "```razor",
      "<RadzenDataGrid Data=@employees AllowPaging=\"true\" PageSize=\"10\"",
      "                AllowSorting=\"true\" AllowFiltering=\"true\">",
      "    <Columns>",
      "        <RadzenDataGridColumn Property=\"@nameof(Employee.FirstName)\" Title=\"First name\" />",
      "        <RadzenDataGridColumn Title=\"Actions\">",
      "            <Template Context=\"e\"><RadzenButton Text=\"Edit\" Click=@(() => Edit(e)) /></Template>",
      "        </RadzenDataGridColumn>",
      "    </Columns>",
      "</RadzenDataGrid>",
      "```",
      "",
      "**Server-side `LoadData`** — set `Count` + `Data` + `LoadData`; the handler receives `LoadDataArgs { Skip, Top, OrderBy, Filter }` (OrderBy/Filter are Dynamic LINQ strings):",
      "```razor",
      "<RadzenDataGrid Count=@count Data=@employees LoadData=@LoadData AllowPaging=\"true\" PageSize=\"10\">",
      "    <Columns><RadzenDataGridColumn Property=\"@nameof(Employee.FirstName)\" Title=\"First name\" /></Columns>",
      "</RadzenDataGrid>",
      "```",
      "```csharp",
      "async Task LoadData(LoadDataArgs args) {",
      "    var query = db.Employees.AsQueryable();",
      "    if (!string.IsNullOrEmpty(args.Filter)) query = query.Where(args.Filter);",
      "    if (!string.IsNullOrEmpty(args.OrderBy)) query = query.OrderBy(args.OrderBy);",
      "    count = query.Count();",
      "    employees = query.Skip(args.Skip ?? 0).Take(args.Top ?? 10).ToList();",
      "}",
      "```",
      "",
      "Selection: `@bind-Value=@selected SelectionMode=\"DataGridSelectionMode.Single\"`.",
    ].join("\n"),
  },
  {
    id: "events",
    title: "Event handlers",
    summary: "Click/Change/Submit wiring and common event-arg types.",
    components: ["RadzenButton", "RadzenDataGrid", "RadzenTemplateForm"],
    markdown: [
      "## Events",
      "",
      "Handlers are `EventCallback`s; pass extra context with a lambda:",
      "```razor",
      "<RadzenButton Text=\"Save\" Click=@(args => OnClick(\"save\")) />",
      "<RadzenTextBox Change=@(value => OnChange(value)) />",
      "```",
      "",
      "Common signatures: button `Click` → `MouseEventArgs`; input `Change` → the typed value; form `Submit` → `TItem` and `InvalidSubmit` → `FormInvalidSubmitEventArgs`; grid `LoadData` → `LoadDataArgs`, `RowSelect`/`RowClick` → `DataGridRowMouseEventArgs<T>`.",
    ].join("\n"),
  },
  {
    id: "layout",
    title: "Page layout",
    summary: "Layout/Sidebar/Body shell and Stack/Row/Column/Card content.",
    components: [
      "RadzenLayout",
      "RadzenHeader",
      "RadzenSidebar",
      "RadzenBody",
      "RadzenStack",
      "RadzenRow",
      "RadzenColumn",
      "RadzenCard",
      "RadzenPanelMenu",
    ],
    markdown: [
      "## Layout",
      "",
      "App shell:",
      "```razor",
      "<RadzenLayout>",
      "    <RadzenHeader><RadzenSidebarToggle Click=@(() => expanded = !expanded) /></RadzenHeader>",
      "    <RadzenSidebar @bind-Expanded=@expanded>",
      "        <RadzenPanelMenu>",
      "            <RadzenPanelMenuItem Text=\"Home\" Icon=\"home\" Path=\"/\" />",
      "        </RadzenPanelMenu>",
      "    </RadzenSidebar>",
      "    <RadzenBody>@Body</RadzenBody>",
      "</RadzenLayout>",
      "```",
      "",
      "Content layout uses `RadzenStack` (`Orientation`, `Gap`, `AlignItems`, `JustifyContent`) and a `RadzenRow`/`RadzenColumn` grid (`Size`, `SizeMD`, `OffsetMD`), often wrapped in `RadzenCard`:",
      "```razor",
      "<RadzenRow Gap=\"1rem\">",
      "    <RadzenColumn Size=\"12\" SizeMD=\"6\"><RadzenCard>Left</RadzenCard></RadzenColumn>",
      "    <RadzenColumn Size=\"12\" SizeMD=\"6\"><RadzenCard>Right</RadzenCard></RadzenColumn>",
      "</RadzenRow>",
      "```",
    ].join("\n"),
  },
  {
    id: "theming",
    title: "Theming",
    summary: "Set a theme with RadzenTheme; free and premium theme names.",
    components: ["RadzenTheme"],
    markdown: [
      "## Theming",
      "",
      "Set the theme once in `App.razor`:",
      "```razor",
      "<RadzenTheme Theme=\"material\" @rendermode=\"InteractiveServer\" />",
      "```",
      "",
      "Free themes: `material`, `material-dark`, `standard`, `standard-dark`, `default`, `dark`, `humanistic`, `humanistic-dark`, `software`, `software-dark`. Premium: `material3`, `fluent` (and dark variants).",
    ].join("\n"),
  },
  {
    id: "dialogs-notifications",
    title: "Dialogs and notifications",
    summary: "Inject DialogService / NotificationService and call them.",
    components: ["RadzenComponents"],
    markdown: [
      "## Dialogs & notifications",
      "",
      "Inject the services (registered by `AddRadzenComponents()`):",
      "```razor",
      "@inject DialogService DialogService",
      "@inject NotificationService NotificationService",
      "```",
      "```csharp",
      "// Confirm / alert",
      "bool? ok = await DialogService.Confirm(\"Delete?\", \"Confirm\");",
      "// Open a component as a dialog",
      "await DialogService.OpenAsync<EditPage>(\"Edit\", new() { [\"Id\"] = id });",
      "// Toast notification",
      "NotificationService.Notify(new NotificationMessage {",
      "    Severity = NotificationSeverity.Success, Summary = \"Saved\", Detail = \"Record saved.\" });",
      "```",
      "",
      "> Requires `<RadzenComponents @rendermode=... />` in your layout.",
    ].join("\n"),
  },
  {
    id: "icons",
    title: "Icons",
    summary: "RadzenIcon uses Material Symbol names; reused as Icon= on controls.",
    components: ["RadzenIcon", "RadzenButton", "RadzenPanelMenuItem"],
    markdown: [
      "## Icons",
      "",
      "`RadzenIcon` renders a Material Symbol by name:",
      "```razor",
      "<RadzenIcon Icon=\"dashboard\" IconStyle=\"IconStyle.Primary\" />",
      "```",
      "",
      "The same names are used as the `Icon` attribute on other components: `<RadzenButton Icon=\"save\" Text=\"Save\" />`, `<RadzenPanelMenuItem Icon=\"home\" Text=\"Home\" />`. Use `IconColor` for a custom color, `IconStyle` for theme severities (Primary/Success/Danger/…).",
    ].join("\n"),
  },
];
